### ISSUE TITLE
Promote ISO standards in units representation

### ISSUE THREAD

**Issue by rdlopes** [design-tokens/community-group#159]
Hi community 🙌,

following up on the [duration description](https://github.com/design-tokens/community-group/blob/main/technical-reports/format/types.md), I noticed we are using the "traditional" unit based on milliseconds.

I'm fine with that, but I'm more on the cross-standards side of things.

Hence my suggestion to add a more css-agnostic way of representing durations (in ms), to onboard with the [ISO 8601 durations](https://en.wikipedia.org/wiki/ISO_8601#Durations).

I know this sounds unfamiliar to all the folks having dealt with milliseconds in CSS history, but for someone who has touched on many things other than CSS, it doesn't sound completely awkward to experiment with cross-standardisation.

I'd love to see W3C standards using standard units representation for duration.

For instance, a duration of a second for a transition, noted `1000ms` could as well be represented in the ISO standard `PT1S`.
This allows for better cross-worlds communication and is more specific than an ever growing set of regex rules.

I would suggest enlarging duration definition to ISO format.
We could think of types like `ms-duration` and `iso-duration`, keeping `duration` type as a default ms format for backward compatibility.

**Comment by romainmenke** [comment]
> for backward compatibility.

This is not really a concern yet as the specification hasn't progressed to this point yet :)
If changes can be made to improve interoperability with other tools and contexts, this would be an ideal time.

**Comment by rdlopes** [comment]
I'm thinking about all the tools developed at this point and catching up with the specification, such as [Style Dictionary](https://amzn.github.io/style-dictionary/#/) which themselves are using [formats](https://amzn.github.io/style-dictionary/#/formats?id=custom-formats).

My context is the following: I was developing for a client a set on services for a workflow tool called [Camunda](https://github.com/camunda), which expresses durations in the ISO 8601 format.
For such services, I have a set of WebComponents reporting changes of states/statuses of such services via a web UI.
I then found myself implementing formatters and renderers to bridge the gap between CSS and backend worlds.

I have created PR #160 to suggest a starting point.

**Comment by romainmenke** [comment]
> I'm thinking about all the tools developed at this point and catching up with the specification, such as [Style Dictionary](https://amzn.github.io/style-dictionary/#/) which themselves are using [formats](https://amzn.github.io/style-dictionary/#/formats?id=custom-formats).

It is best to consider style dictionary or any other existing format as a completely separate thing. It is impossible to create a specification and have backwards compatibility with these projects.

**Comment by c1rrus** [comment]
Thank you for raising this issue (and also opening a PR for it), @rdlopes. While I think it is generally a good idea to lean on other, suitable standards rather than re-inventing the wheel, I'm not convinced the ISO 8601 format would be appropriate in this instance.

This format is for specifying _design_ tokens, so it's primarily catering to teams and tools involved in the creation of graphical user interfaces. In that context, the primary use-case for duration tokens is animation. We expect them to be used to express durations and/or delays that get used in UI animations. It's therefore reasonable to expect the actual duration values to be quite short. Most UI animations/transitions I've seen will be fractions of a second and a few seconds at most. Duration values in the order of minutes, hours or even days are _very_ unlikely.

Furthermore, a quick sampling of tools and platforms other than CSS suggest that they often use milliseconds or seconds wherever animation durations can be set:

* [Figma's animation settings](https://help.figma.com/hc/en-us/articles/360040314193-Guide-to-prototyping-in-Figma#Create_interactions_and_animations) use millisecond values
* [Android's animation & transition APIs](https://developer.android.com/guide/topics/graphics/prop-animation) use millsecond values
* [Animations in iOS](https://www.raywenderlich.com/5304228-ios-animation-tutorial-getting-started) appear to use values in seconds

I think it's therefore reasonable to assume that UI designers, developers and other users of design tokens will be familiar with expressing durations in (milli)seconds.

I'm no expert in [ISO 8601 durations](https://en.wikipedia.org/wiki/ISO_8601#Durations), but it looks like you could express `123ms` as `PT0.123S`, so _technically_ there's no problem using it. However, considering the above, I'd argue that our current `123ms` syntax will be more readable and familiar to our intended audience than `PT0.123S`.

I realise that you're proposing to use ISO 8601 _in addition to_ the existing syntax. However, given the reasons above, I don't think it really adds any benefit to users of our format but it would add complexity to parsers and people learning the format. My preference is therefore to reject this proposal.

(If we expected people to often use much longer durations (minutes, hours, etc.), then this would be a good idea and I'd be in favour of it. But I seriously doubt people will be doing that in our format)

**Comment by c1rrus** [comment]
Thank you for raising this issue (and also opening a PR for it), @rdlopes. While I think it is generally a good idea to lean on other, suitable standards rather than re-inventing the wheel, I'm not convinced the ISO 8601 format would be appropriate in this instance.

This format is for specifying _design_ tokens, so it's primarily catering to teams and tools involved in the creation of graphical user interfaces. In that context, the primary use-case for duration tokens is animation. We expect them to be used to express durations and/or delays that get used in UI animations. It's therefore reasonable to expect the actual duration values to be quite short. Most UI animations/transitions I've seen will be fractions of a second and a few seconds at most. Duration values in the order of minutes, hours or even days are _very_ unlikely.

Furthermore, a quick sampling of tools and platforms other than CSS suggest that they often use milliseconds or seconds wherever animation durations can be set:

* [Figma's animation settings](https://help.figma.com/hc/en-us/articles/360040314193-Guide-to-prototyping-in-Figma#Create_interactions_and_animations) use millisecond values
* [Android's animation & transition APIs](https://developer.android.com/guide/topics/graphics/prop-animation) use millsecond values
* [Animations in iOS](https://www.raywenderlich.com/5304228-ios-animation-tutorial-getting-started) appear to use values in seconds

I think it's therefore reasonable to assume that UI designers, developers and other users of design tokens will be familiar with expressing durations in (milli)seconds.

I'm no expert in [ISO 8601 durations](https://en.wikipedia.org/wiki/ISO_8601#Durations), but it looks like you could express `123ms` as `PT0.123S`, so _technically_ there's no problem using it. However, considering the above, I'd argue that our current `123ms` syntax will be more readable and familiar to our intended audience than `PT0.123S`.

I realise that you're proposing to use ISO 8601 _in addition to_ the existing syntax. However, given the reasons above, I don't think it really adds any benefit to users of our format but it would add complexity to parsers and people learning the format. My preference is therefore to reject this proposal.

(If we expected people to often use much longer durations (minutes, hours, etc.), then this would be a good idea and I'd be in favour of it. But I seriously doubt people will be doing that in our format)

**Comment by rdlopes** [comment]
Hi @c1rrus, thanks for the clarification.

Do I understand that duration semantics will only and always be meant to 
- represent animations in design?
- be used by the CSS community?

Because, in that case, I agree with you; there's no point trying to generalize or be cross-platform.

**Comment by c1rrus** [comment]
@rdlopes: The format editors have reviewed this issue and decided to close it. We thank you for your suggestion, but as per my earlier comment, we think keeping just the `ms` format for durations is more appropriate given our format's intended audience.

To answer your 2 questions...

> Do I understand that duration semantics will only and always be meant to
>
> * represent animations in design?

Yes. (UI) animations are the primary use-case we expect duration design tokens to be used for. While people _might_ find other uses for duration design tokens, we're not going to optimize for that.

> * be used by the CSS/styling community?

If by "styling community" you mean people who create digital user interfaces, then yes. :-)

However, bear in mind that, design tokens are tool- and platform-agnostic, so CSS code is just one possible output from a design token. Code for Android, iOS and other platforms could also be generated. Also, designers may (one day) be able to import and use design tokens within their tools too.
