### ISSUE TITLE
Dimensions on Android, iOS, etc

### ISSUE THREAD

**Issue by inktomi** [design-tokens/community-group#208]
[8.2 Dimensions](https://design-tokens.github.io/community-group/format/#dimension) specifies that dimensions MUST be followed by either "px" or "rem". 

After the example, it's pointed out that px may not work on every platform, for example on Android there are dp and on iOS there are pt units. 

The issue is that on Android, there are not _only_ `dp` (density independent pixels). There are also `sp` (scalable pixels, used for text), `px` for pixels etc. 

How would a spec indicate which of these should be used on Android, when the spec enforces that it only contain `px` and `rem` units?

**Comment by c1rrus** [comment]
The design tokens defined in a DTCG file are intended to be platform agnostic. It's the job of a translation tool (like [Style Dictionary](https://amzn.github.io/style-dictionary/) or [Cobalt](https://careers.jpmorgan.com/us/en/professionals)) to convert those tokens into code. Part of that translation may include converting the DTCG units into whatever the platform-specific equivalents are.

As you've noted, the `px` unit in a DTCG file is equivalent to `dp` on Android, so a token value like `32px` would probably get exported as `32dp`.

> The sp unit is the same size as a dp, by default, but it resizes based on the user's preferred text size
>
(source: https://developer.android.com/training/multiscreen/screendensities)

So an Android `sp` is the same kind of concept as CSS `rem` (which is the other permitted dimension unit in DTCG files), except that it's relative to 1dp rather than the base font size like `rem` is in CSS.

Therefore: `1rem` == `16sp`.

So to have design tokens that would get exported as `sp` values in Android, use the `rem` unit and divide your value by 16.

For example: `{ "$value": "2rem", "$type": "dimension" }` should be exported to `32sp` on Android.

**Comment by c1rrus** [comment]
Yeah, I probably didn't word that well. What I meant was: To go from a target `sp` value to the equivalent `rem` value, you'd need to divide by 16. Going the other way, you'd need to multiply. I think you get the idea :-)

I'll go ahead a close this issue since the original question's been answered. Feel free to raise more issues if you have other questions.
