### ISSUE TITLE
Alias $type inheritance?

### ISSUE THREAD

**Issue by drwpow** [design-tokens/community-group#236]
Was digging into alias behavior a bit, and I had a few question about alias `$type`s. What are peoples’ thoughts on whether any of the following are **valid** or **invalid**? Also I may have missed a previous conversation or part of the spec that applies to this.

#### Omitting $type

Is this valid?

```json
{
  "color": {
    "a": { "$type": "color", "$value": "#336699" },
    "b": { "$value": "{color.a}" }
}
```

#### $type mismatch

Will `color.b` be a color, and be validated as such (sort of an extension of the previous one)?

```json
{
  "color": {
    "a": { "$type": "color", "$value": "#336699" },
    "b": { "$type": "dimension", "$value": "{color.a}" }
}
```

And an even bigger question: **is declaring ANY `$type` on an alias invalid?**

#### $type inheritance

Will the inherited `$type` also apply to the alias? (and override any possible `$type` the alias may have)?

```json
{
  "base": {
    "$type": "color",
    "a": { "$value": "#336699" }
  },
  "semantic": { "$value": "{base.a}" }
}
```

---

In all of these, I’d like to **reduce error** as much as possible, and I can’t think of a good reason for even declaring `$type` on aliases because there’s at best there’s duplication; at worst there’s the possibility of a conflict. And wondering **when it’s helpful to err, when it’s helpful to warn, and when it’s helpful to do nothing (silently work)**

**Comment by whoisryosuke** [comment]
I think the `$type` alias is to allow for parsers just to know to check an object and its properties. Otherwise how would it know to check for colors? It’d have to assume a token structure (like all colors are under top level `color` property).

It also helps explicitly define the type of the token, since you might want to mix tokens to achieve another (like combining opacity number and RGB color to make a RGBA new color). Or for example, if you multiply `fontSize` and a `spacing` token, what is the type of the result? Might get weird for parsers. 

I do think there you have a great idea of not including it every time though. It seems verbose and makes it difficult to manually parse JSON without a tool to strip the noise. Not sure how to practically achieve that without an explicit structure or some other system to accommodate for the inference of types. 

Also this issue emphasizes the need for a section of the docs on parsing, and expectations the spec has - to create some consistency between tooling.

**Comment by drwpow** [comment]
> I think the `$type` alias is to allow for parsers just to know to check an object and its properties. Otherwise how would it know to check for colors? It’d have to assume a token structure (like all colors are under top level `color` property).

Well that’s just the thing though—parsers actually have to validate aliases currently. Aliases _have_ to be non-circular. And non-aliases have to be valid tokens. By just accepting an unvalid schema at face-value, the user will get errors with no clear action on how to fix it. So parsers actually _do_ have to scan the alias and know it’s referring to a color anyway, and there’s no way for them to avoid having that work (or they’d be bad, hard-to-use-tools). But I was more interested in exploring whether that’s **an error** to show to the user “fix this!” or if it just silently works

> Also this issue emphasizes the need for a section of the docs on parsing, and expectations the spec has - to create some consistency between tooling.

💯!

**Comment by ilikescience** [comment]
The spec lists out the following resolution order:

> A token's type can be specified by the optional $type property. If the $type property is not set on a token, then the token's type MUST be determined as follows:
> - If the token's value is a reference, then its type is the type of the token being referenced.
> - Otherwise, if any of the token's parent groups have a $type property, then the token's type is inherited from the closest parent group with a $type property.
> - Otherwise, the token's type is whichever of the basic JSON types (string, number, boolean, object, array or null) its value is.

So, in your examples

```json
{
  "color": {
    "a": { "$type": "color", "$value": "#336699" },
    "b": { "$value": "{color.a}" }
}
```

This is valid, and `color.b` has a type of `color`.

```
{
  "color": {
    "a": { "$type": "color", "$value": "#336699" },
    "b": { "$type": "dimension", "$value": "{color.a}" }
}
```
This is invalid; the spec says that a token with the type `dimension` must be "a string containing a number (either integer or floating-point) followed by either a "px" or "rem" unit". Since `{color.a}` doesn't match this, this is an invalid token.

```
{
  "base": {
    "$type": "color",
    "a": { "$value": "#336699" }
  },
  "semantic": { "$value": "{base.a}" }
}
```

This is valid, and `semantic` would get resolved to having the type of `color` (since `base.a` has the type of `color`). 

The spec is pretty unambiguous about these, though it might need a bit more language to acknowledged that a referenced token might inherit its type, too, either from its group or another reference.

> I can’t think of a good reason for even declaring $type on aliases

Yes, almost any type on a token with a value like `{base.a}` will result in an invalid token. There's probably some weird edge cases where you can have a token with a `fontFamily` type which, according to the spec, would be valid, resulting in css like `font-family: '{base.a}'` ... but resolving this would probably create substantially more edge cases than it would solve.

**Comment by drwpow** [comment]
> There's probably some weird edge cases where you can have a token with a `fontFamily` type which, according to the spec, would be valid, resulting in css like `font-family: '{base.a}'` ... but resolving this would probably create substantially more edge cases than it would solve.

Oh I hadn’t even thought of this, but you’re right just evaluating a token’s `$type` by parsing its value could lead to many errors. Especially if `string` tokens ever were accepted (not that they are in the DTCG now, but mainly thinking of Figma variables’ current implementation where string types can refer to colors or typography values).

> The spec is pretty unambiguous about these, though it might need a bit more language to acknowledged that a referenced token might inherit its type, too, either from its group or another reference.

Agreed—I think clarifying this would help. The resolution definition you provided earlier _implies_ this, but doesn’t outright explicate it, and it could be clearer.

Thanks for clarifying! This seems like it’s not really ambiguous, then, how the spec is interpreted. More just a possible documentation TODO of “should alias types get a little more specific regarding this behavior or not”.

**Comment by doozMen** [comment]
In addition to this comprehensive explanation, I would like to address an issue we face when parsing the Token Studio dynamic JSON that is based on this spec into a type-safe system in Swift. Type safety ensures that our code adheres to the specification. Below, you can see how we define the specification related to the types in Swift.

Note: To understand the Swift code, familiarity with the concept of enums with associated values is required. You can find more information [here](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/enumerations/). Additionally, understanding [Codable](https://developer.apple.com/documentation/swift/codable) might be necessary.

```swift
public enum Token: Codable, Hashable, Sendable {
    case assetLink(RefOrValue<Asset>)
    case boolean(RefOrValue<Boolean>)
    case boxshadow(RefOrValue<BoxShadow>)
    case border(RefOrValue<Border>)
    case color(RefOrValue<ColorResult>)
    case dimension(RefOrValue<Math>)
    case fontFamily(RefOrValue<FontFamily>)
    case fontSize(RefOrValue<Pixel>)
    case fontWeight(RefOrValue<FontWeight>)
    case format(RefOrValue<Format>)
    case lineHeight(RefOrValue<LineHeight>)
    case number(RefOrValue<Math>)
    case size(RefOrValue<Pixel>)
    case textDecoration(RefOrValue<TextDecoration>)
    case typography(RefOrValue<Typography>)
    case composition(RefOrValue<Composition>)

    public enum RawType: String, Codable, CaseIterable, Sendable {
        case assetLink = "asset"
        case boolean
        case border
        case boxshadow = "boxShadow"
        case color
        case composition
        case dimension
        case fontFamily = "fontFamilies"
        case fontSize = "fontSizes"
        case fontWeight = "fontWeights"
        case format
        case lineHeight = "lineHeights"
        case number
        case size = "sizing"
        case textDecoration
        case typography
    }
}
```
The types in the enum `Token.RawType` are based on the Token Studio specification. The challenge arises when we try to transform this specification into Swift/Kotlin/web code. We need to convert these types into a format that can be displayed on the screen. This transformation groups the types into a `UIType`, which represents something that can actually be rendered.

The specification poses a problem in determining which file to write the code to, as we can only identify the type if it is resolved. However, we do not want to resolve every alias at the moment we define the file to write to (this is an optimization to parse asynchronously). Hence, we have this mapping:

```swift
extension Token {
    var uiType: UIType {
        switch self {
        case .assetLink:
            return .assetLink
        case .boolean:
            return .uiBoolean
        case .boxshadow:
            return .boxShadow
        case .border:
            return .border
        case .color(.value(.color)):
            return .color
        case .color(.value(.gradient)):
            return .gradient
        case .color(.value(.modified)):
            return .color
        case .color(.reference(_)):
            // TODO: what to do here?
            return .color
        case .dimension:
            return .dimension
        case .fontFamily:
            return .fontFamily
        case .fontSize:
            return .fontSize
        case .fontWeight:
            return .fontWeight
        case .format:
            return .format
        case .lineHeight:
            return .assetLink
        case .number:
            return .number
        case .size:
            return .sizing
        case .textDecoration:
            return .textDecoration
        case .typography:
            return .typography
        case .composition:
            return .composition
        }
    }
}
```

The code includes a `TODO` because, according to the specification, a color can also be a gradient. However, to display them, the schema for a gradient differs significantly from a single color. For example, a single color might be represented as `color=hex`, while a gradient could be represented as `colors=[(hex, 50%),(hex, 10%),(hex, 30%)]`.

In XML, each node with a value or reference has a class that describes its type. We propose a similar approach here by adding the type reference.

Might I suggest that a reference is simply another JSON node, like color, with a type and a value. If the type is a reference, then the value is also a JSON node with a path and a type describing the destination type.

```json
{
  "background": {
    "gradient": {
      "value": {
        "path": "gradient.default.1",
        "type": "gradient"
      },
      "type": "reference"
    }
  }
}
```
This approach provides a clear and structured way to handle dynamic JSON parsing in a type-safe manner, ensuring that our code adheres to the specification and can be rendered appropriately on the screen.

We face this issue in projects for a media group based in Belgium called Mediahuis.

**Comment by nclsndr** [comment]
I thought a lot about the issues you mention @doozMen, and I landed on the same conclusion: the json tree lacks data.
That said, the format specification aims for user-friendliness rather than ease of parsing when tradeoffs like this one shows up. I don't think we'll get the format to host the missing pieces.

BUT, we can still specify a mapping for allowed aliasing matches among tokens:

```ts
// Example with Border token
const borderTokenTypeMapping = {
  _unionOf: [
    { _tokenType: borderTokenTypeName },
    {
      _mapOf: {
        color: colorTokenTypeMapping,
        style: strokeStyleTokenTypeMapping,
        width: dimensionTokenTypeMapping,
      },
    },
  ],
} satisfies TokenTypesMapping;
```
[Full version of the code](https://github.com/nclsndr/design-tokens-tools/blob/main/packages/w3c-design-tokens-parser/src/definitions/tokenTypes.ts#L98-L222)

**Comment by drwpow** [comment]
I’m happy to close the issue, yeah. There might be a TODO on just adding some additional clarification in the documentation, but no spec changes are necessary IMO.

**Comment by doozMen** [comment]
> I thought a lot about the issues you mention @doozMen, and I landed on the same conclusion: the json tree lacks data. That said, the format specification aims for user-friendliness rather than ease of parsing when tradeoffs like this one shows up. I don't think we'll get the format to host the missing pieces.
> 
> BUT, we can still specify a mapping for allowed aliasing matches among tokens:
> 
> ```ts
> // Example with Border token
> const borderTokenTypeMapping = {
>   _unionOf: [
>     { _tokenType: borderTokenTypeName },
>     {
>       _mapOf: {
>         color: colorTokenTypeMapping,
>         style: strokeStyleTokenTypeMapping,
>         width: dimensionTokenTypeMapping,
>       },
>     },
>   ],
> } satisfies TokenTypesMapping;
> ```
> 
> [Full version of the code](https://github.com/nclsndr/design-tokens-tools/blob/main/packages/w3c-design-tokens-parser/src/definitions/tokenTypes.ts#L98-L222)
> 
> Beside this off-initial-topic answer, shouldn't we close this issue?

Thanks for taking my off-topic suggestion into account. Your suggestion to have a mapping slightly slows down the parsing and at least for me is less readable but if this is possible is there an issue I can track to when this mapping description lands in the spec?

**Comment by nclsndr** [comment]
> Your suggestion to have a mapping slightly slows down the parsing and at least for me is less readable

Agreed on that part @doozMen. I do not completely buy this rationale neither.

> is there an issue I can track to when this mapping description lands in the spec

I guess the current state is the following:
- For primitives (like color, dimension…), they can be aliased by their own type only - even though this information is not written down.
- For composites, the mapping is described within the spec already - [border example](https://tr.designtokens.org/format/#border)
