### ISSUE TITLE
Object vs Array

### ISSUE THREAD

**Issue by dbanksdesign** [design-tokens/community-group#55]
```json
{
  "token name": {
    "value": "token value"
  }
}
```

The structure in the example above is a JSON object, an unordered set of name/value pairs.

- Objects can't contain members with duplicate keys
- Ordering of object members may not be preserved (as per [RFC 7159](https://tools.ietf.org/html/rfc7159#section-4)), meaning token retrieval may or may not result in the same ordering as the input

Please raise concerns if these limitations create problems for implementers.

**Comment by c1rrus** [comment]
I believe it would useful if our format provided authors with a means to express that tokens in a group should be presented in a specific order. For example, if you have a bunch of tokens representing tints and shades of a colour then it's nice if they can be displayed in a specific order. Imagine a style guide generator that renders them as colour swatches.

Given that our basis is JSON, arrays feel like the most convenient way of achieving that. Doing that means that there are 2 flavours of groups:

* Object-based groups (whose tokens and nested groups do **not** have a defined order)
* Array-based groups (whose tokens and nested groups **do** have a defined order)

However, introducing array groups also brings a few challenges:

**Token names**
Right now, a token's name its key in the parent group. For example, to define a token called "my awesome token" you'd do something like this:
```jsonc
{
  "my awesome token": {
    "value": "#ff0000",
    "type": "color"
  }
}
```

But, if that's in an array, there is no (explicit) key:

```jsonc
[
  {
    // what is the name of this token??
    "value": "#ff0000",
    "type": "color"
  }
]
```

I had grappled with this a bit in my [UDT experiment](https://udt.design/), and landed on the following, which I propose as a potential solution for our spec:

* The token object itself can have an _optional_ `name` property to declare the token's name.
* If a token in an object has a `name` attribute, then that takes precedence over the parent object's key
* If a token in an array does _not_ have a `name` attribute, then the array index is used as its name

For example:

```jsonc
{
  "object group": {
    "token 1": {
      "value": 42
      // This token's name is: "token 1"
      // Its path is: "object group" / "token 1"
    }

    "token 2": {
       "name": "actual token name",
       "value": "hello world"
      // This token's name is: "actual token name" (note how the "token 2" key is now ignored)
      // Its path is: "object group" / "actual token name"
    }
  },

  "array group": [
    {
      "value": 99
      // This token's name is: "0" (since it has no name property, the array index is used instead)
      // Its path is: "object group" / "0"
    },

    {
      "value": 24,
      "name": "token name"
      // This token's name is: "token name"
      // Its path is: "object group" / "token name"
    }
  ]
}
```

_Aside:_ Another benefit of introducing the optional `name` property is that it could enable authors to name tokens with things that are reserved keywords in our spec. It's probably a very niche edge-case, but let's imagine you wanted to name your token "description". Normally, this wouldn't be possible because `description` is a reserved keyword used to add a text description to tokens and groups. _But_ you could work around it like so:

```jsonc
{
   "description": "This is the description of this group!",
   "ignored": {
      // This is a token whose name is "description"
      name: "description",
      value: 42
    }
}
```


**Group properties**
We currently allow groups to have their own `description` properties, and we've been discussing adding support more more. This works fine for the existing object-based groups where those are "special" keys (note to self: We really need to add a list of reserved keywords which cannot be used for token or group names to our spec!). But we can't do the same thing for an array group.

In my UDT experiments, I came up with the following potential solution. It's a bit clunky though...

* An array group can be written in 2 ways:
    * A plain JSON array, which directly contains the tokens and nested groups
    * A JSON object with a `tokens` property which is an array that contains the tokens and nested groups.
* When authoring an array group using the object syntax, group properties like `description` can be added to that object
    * No other properties may be added to the object though

Example:
```jsonc
{
  // This array group cannot be given a description or any other group property
  "array-style array group": [
     {
       // Token name: "red"
       // Token path: "array-style array group" / "red"
       "name": "red",
       "value": "#ff0000"
     }
  ],

  // But this one can have those things..
  "object-style array group": {
    "description": "The group's description",
    // This array group's actual tokens go in here...
    "tokens": {
       {
         // Token name: "green"
         // Token path: "object-style array group" / "green"
         "name": "green",
         "value": "#00ff00"
       }
    }
  }
}
```

A parser can distinguish between an object group, a token and an object-style array group as follows:

* Does the object have a `value` property? If yes, it must be a token. Otherwise...
* Does the object have a `tokens` property? If yes, it must be an object-style array group. Otherwise...
* It must be an object group

**Root level**
One of things we've discussed but not yet added to the spec is having some kind of property indicating the version of the DTCG spec that the file conforms to. It's conceivable there may be other file-level properties we need to add in future too (e.g. a list of other token files to import or include).

For sake of this point, let's imagine we decided to add the spec version by having a mandatory `$schema` property at the top level, whose value was a URL to a JSON schema corresponding the DTCG spec version. For example:

```
{
  "$schema": "https://designtokens.org/spec/v1/",
  // tokens go here...
}
```

That would require every DTCG token file to be an object at the top level (note, in plain JSON it's permissible for the top level to be any JSON value - array, string, number...). I think that by itsefl is fine and the current spec draft pretty much mandates that anyway.

_But_, if we decide to introduce array groups, then the consequences for that top-level group would be:

* **Either**, it can only be an object-style group, meaning that you cannot specify an order to the top-level groups and/or tokens in your file
* **Or**, it necessitates something like the object-style array groups I proposed in the previous section. That way, the top level of your file can be an array group (if it contains a `tokens` propert) or an object group otherwise.

My preference would be for the latter.

What do you think?

**Comment by kevinmpowell** [comment]
@c1rrus you raise a lot of interesting points here. I think some of which could be moved to the newly created #72 to discuss file & group-level properties.

My preference is to only support object style tokens. The "documentation sorting" use case doesn't rank high enough in my mind to add the additional complexity to support arrays in the spec. Having two syntaxes to support will be challenging to document, and challenging for vendors to implement.

If we need to solve a "sorting" use case, then I propose a "sortOrder" token property that could be added at any level. (I'm not convinced we need this).

I think documentation/sorting use cases can be handled within tools. For example something like Figma could have toggles to let you sort colors by brightness, alphabetically by name, or by opacity. A doc tool could do the same. If there are other use cases that justify preserving order in the actual spec I'd like to understand those.

**Comment by ivnmaksimovic** [comment]
@c1rrus I like the idea about optional "name" property, but I think that example with the path you provided might create some confusion. You propose that "path" is "object group" / "actual token name". But I assume that if you ask anyone familiar with json format, what is the path of the token 2, the answer will probably be "object group" / "token 2". No need to check the documentation for such a trivial question, right?

```
{
  "object group": {
    "token 2": {
       "name": "actual token name",
       "value": "hello world"
      // This token's name is: "actual token name" (note how the "token 2" key is now ignored)
      // Its path is: "object group" / "actual token name"
    }
  }
}
```

**Comment by c1rrus** [comment]
@kevinmpowell Ah! I just realised this issue is referenced from the tokens chapter, not the groups one. I had mistakenly assumed it was about groups. Sorry for any confusion caused!

I certainly agree that properties within tokens shouldn't need a predictable order, so also agree that tokens should only ever be objects.

For _groups_ I think there could potentially be value in being able to order the tokens and/or groups within them (and that's what my proposals above were for):

* It might allow teams to have a consistent ordering of tokens across design tools, docs and in code.
* For style guides or other documentation being generated from token files, it would give authors control over how sections are ordered.
* There may be things like brand colors where it's desirable to list them in the same order as they appear in brand guidelines, and that might not be in order of lightness or something like that.

That being said, these are hunches. The real-world demand for this kind of stuff is unproven at the moment (unless someone is able to offer evidence to the contrary). Also, as you point out, tools can probably cover many uses by having the ability to sort tokens based on various criteria when displaying them to users.

I'm therefore leaning towards only having object groups, and thus no explicit ordering, in our first version of the spec.

If the need for ordering arises later on, we can re-consider appraches like the ones I proposed or your `sortOrder` property idea. Either of could be added without breaking backwards compatibility.

**Comment by c1rrus** [comment]
@ivnmaksimovic 

> [...] I think that example with the path you provided might create some confusion. You propose that "path" is "object group" / "actual token name". But I assume that if you ask anyone familiar with json format, what is the path of the token 2, the answer will probably be "object group" / "token 2". No need to check the documentation for such a trivial question, right?

I agree it's a bit unintuitive when looking at the raw JSON (and perhaps it's not a great proposal for that reason). On the other hand, saying that a `name` attribute always overrides the index / key of the enclosing array / object group also has a nice consistency to it. I think it might be more confusing if it only has an effect in arrays but gets ignored otherwise.

Also, there may be some rare edge-cases where it's useful to be able to tweak the path. For example, `description` is a reserved word in the spec as it is used to provide description text for tokens and groups. Therefore, you cannot have a token or group whose name is `description`. However, using the `name` attribute you could:

```jsonc
{
  "card": {
    "color": {
      "title": {
        "type": "color",
        "value": "#000000"
      },
      "ignored": {
        "name": "description",
        "type": "color",
        "value": "#777777",
      }
    }
  }
}
```

An export tool that supports our format would most likely use a token's path to generate variable names to output. So, if exporting to SASS, the above token file might produce something like this:

```scss
$card-color-title: #000000;
$card-color-description: #777777; // probably more appropriate than $card-color-ignored, right?
```

**Comment by ivnmaksimovic** [comment]
Not sure if this or https://github.com/design-tokens/community-group/issues/72 is better place for this as this tackles both issues. Inspired by some of @c1rrus suggestions and `tokens` prop I made this few simple rules. Benefit would be that there would be just one reserved word for token name ("tokens"). Both object and arrays would be supported, and I see no need for exceptions and special cases.

There is just few things to think about `token`, `tokens group`, and `tokens` key.

## Token
Can contain:
  - Either just value.
  - Either token properties like value, type, description, name, anything. In this case `value` is mandatory.

May not contain:
  - `tokens` prop. This would actually make it a tokens group and all the props would be group props. Even `value` would be just another group prop.

## Tokens group
Must contain:
  - `tokens` prop.

Can contain:
  - none or any number of other group properties like type, description, name, anything... Even `value` would be just another group prop.

`filename.tokens` or `filename.tokens.json` is a tokens group just as any other group containing `tokens`.

## Tokens prop
Can contain:
  - Individual tokens
  - Token groups

It can be both object or array format.

## Summary
- root level of json is a tokens group.
- If some value has a `tokens` prop, it makes it a tokens group.
- If some value doesn't have tokens, it makes it an individual token, so it must have value prop. Unless it is a simple key/value pair where value is value.

That is all :)

## Examples

- token with just a value:
`"primaryColor": "#00ff00"`

- token with properties, where value is mandatory:
```json
"primaryColor": {
    "value": "#00ff00",
    "type": "color",
    "description": "use this color everywhere",
    "name": "Main Color",
    "anything": "You can use any key names and any number of properties, except `tokens` if you want this to be an individual token, not a group. Only `value` is mandatory for an individual token."
}
```

- root level tokens group. You can't add group properties in root level unless you add `tokens` prop. However this is nice option for micro themes.
```json
{
    "primaryColor": "#ff00ff",
    "secondaryColor": "#0000cc",
    "complexToken": {
        "value": "#ff0000",
        "type": "color",
        "description": "description"
    }
}
```

- root level tokens group as array.
```json
[ "#000000", "#ffffff", "#cccccc", "#ccff33"]
```

- adding `tokens` prop makes a tokens group, not an individual token, and all the props will be group props. Even value will be just a non mandatory prop on a group, not the token value.
```json
"color": {
    "value": "Not really a token value, since this is a tokens group.",
    "type": "color",
    "description": "these are our colors",
    "name": "Color Pallete",
    "tokens": {
        "primary": "#00ff00",
        "secondary": "another individual token or tokens group here",
        "value": "value does not mean anything here also since this is also a token group",
        "complexToken": {
            "value": "#ff0000",
            "type": "color",
            "description": "description"
        }
    }
}
```

### Complex example including arrays and how it could translate to css variables

mybrand.tokens
```json
{
    "type": "color",
    "description": "tokens group description",
    "value": "just another prop on the tokens group",
    "tokens": {
        "color": {
            "type": "color",
            "tokens": {
                "primary": {
                    "description": "primary colors and variations",
                    "tokens": {
                        "light": "#000000",
                        "dark": "#ffffff"
                    }
                },
                "secondary": "#00ff00",
                "terciary": {
                    "name": "accent",
                    "value": "#cc55ff"
                }
            }
        },
        "spacing": {
            "horizontalWithObjects": { "s": "2px", "m": "4px", "l": "8px" },
            "verticalWithArrays": [ "2px", "4px", "8px" ],
            "universalWithArraysAndExtraProps": {
                "description": "description",
                "moreProps": "more props",
                "tokens": [
                    { "name": "s", "value": "2px" },
                    { "name": "m", "value": "4px" },
                    { "name": "l", "value": "8px" }
                ]
            }
        },
        "deplyNestedForNoGoodReason": {
            "description": "This group has tokens",
            "tokens": {
                "description": "Instead of actuall tokens just a another tokens group is nested here. Not much sense to design your tokens like this, but things will not break.",
                "type": "dimension",
                "tokens": {
                    "description": "this group will finally have real tokens",
                    "tokens": {
                        "t1": 1,
                        "t2": 2
                    }
                }
            }
        },
        "crazyNames": {
            "description": "Tokens can use any name except `tokens`, including value, type or description",
            "tokens": {
                "type": 1,
                "value": 2,
                "description": 3
            }
        }
    }
}
```
Compiled to CSS

```css
.some-css-selector {
    --color-primary-light: "#000000";
    --color-primary-dark: "#ffffff";
    --color-secondary: "#00ff00";

    --color-terciary: "#cc55ff";
    /* or maybe use name
    --color-accent: "#000000";
    */

    --spacing-horizontalWithObjects-s: "2px";
    --spacing-horizontalWithObjects-m: "4px";
    --spacing-horizontalWithObjects-l: "8px";

    --spacing-verticalWithArrays-0: "2px";
    --spacing-verticalWithArrays-1: "4px";
    --spacing-verticalWithArrays-2: "8px";

    --spacing-universalWithArraysAndExtraProps-0: "2px";
    --spacing-universalWithArraysAndExtraProps-1: "4px";
    --spacing-universalWithArraysAndExtraProps-2: "8px";
    /* or maybe take name
    --spacing-universalWithArraysAndExtraProps-s: "2px";
    --spacing-universalWithArraysAndExtraProps-m: "4px";
    --spacing-universalWithArraysAndExtraProps-l: "8px";
    */

    --deplyNestedForNoGoodReason-t1: 1;
    --deplyNestedForNoGoodReason-t2: 2;

    --crazyNames-type: 1;
    --crazyNames-value: 2;
    --crazyNames-description: 3;
}
```

**Comment by ChucKN0risK** [comment]
Reviewed by the spec editors on 2021-11-02

**Decision**
We've decided to stick with objects as think ordering is not a big enough use case for the spec itself to handle. We also think this could be directly handled by toolmakers.

We’re closing this issue for now, but may reopen it in the future if needed.
