### ISSUE TITLE
Token name character restrictions

### ISSUE THREAD

**Issue by kevinmpowell** [design-tokens/community-group#60]
## Character restrictions in token names
Should the specification restrict the name property to a specific Unicode range or make certain characters invalid at the start/middle/end of a name (such as white space, line breaks…)? If so, what characters and why? Should emoji be allowed in token names?

Examples:
```
{
  '      space-at-the-beginning': {
    value: 50\
  },
  {
    'color⚽️': {
      value: '#445566'
  }
}
```

**Comment by c1rrus** [comment]
In the spirit of the DTCG's "inclusive" principle, my vote would be to _not_ impose any restrictions. Folks around the world may well want to name tokens and groups using their native languages and scripts and those won't always be A - Z. And, if someone wants to throw some emoji or Klingon in there too, then who am I to say no :-)

This approach does introduce some potential challenges though:

## Name clashes after conversions
Export tools like Style Dictionary and Theo will typically take a source token name and convert it into a variable name that follows the rules and conventions of the programming language they're outputting. E.g. a token named "Acid Green" might get turned into camel case `acidGreen` for JavaScript or kebab case `$acid-green` for SASS.

These conversions will often trim off leading and trailing whitespace in the source name. Also, the case may be ignored (e.g. when outputting to kebab case all letters are converted to lowercase). So there can be situations where a token file has different tokens with names that differ only in things like whitespace or case. Their converted names in the output might therefore be identical and cause clashes. For example:

```jsonc
{
   "      Acid Green": { "type": "color", "value": "#82ff4d" },
   "acid    green   ": { "type": "color", "value": "#abcdef" },
}
```

Might get exported as SASS variables like this:

```scss
$acid-green: #82ff4d;
$acid-green: #abcdef;
```
...which probably not what you want.

That being said, these scenarios are probably rare. Also, it might only be certain kinds of tools (e.g. export tools) fir which this is even a problem - a GUI tool might just display the token name as is and not need to convert it in any way. I therefore think it's reasonable to just let tools deal with this as they see fit. E.g. report a warning or error to the user, or tweak the output name to keep it unique (e.g. append a number to it something like that).


## Invalid names after conversions
Some programming languages may impose restrictions on their variable names (e.g. in JavaScript a variable name cannot begin with a digit). It's therefore likely that, without restrictions, some token names might not be easily converted to variable names in code.

However, as with the previous point, I think this is something tools can deal with. They could warn the user, omit characters that aren't allowed in the syntax of the target language, prepend or append things as needed, etc.

If a design system team is facing issues because a name they've given a token doesn't work in one or more platforms they need to support, then perhaps they need to choose a different name for their token.


## Implications for aliases
Perhaps not an issue per se, but just wanted to point this out for completeness. If we do not restrict the characters that can be used for token and group names, then we need to cater for that in our reference syntax:

* Characters that are part of the reference syntax (`{`, `.` and `}`) need to be escaped somehow if they occur in a token or group name that is used in the reference.
* Each segment of the reference needs to be an _exact_ match to the corresponding token or group name (so whitespace, case, etc. all need to match exactly).

For example:

```jsonc
{
  "group 1": {
    "token 1": {
      "value": 42
    },
    "   Awkward.to{REFERENCE}  ": {
      "value": 99
    }
  },

  "alias 1": {
    "value": "{group 1.token 1}"
    // This alias token's value will resolve to 42
  },

  "alias 2": {
    // Perhaps we can use backslashes to escape special characters in a reference?
    "value": "{group 1.   Awkward\.to\{REFERENCE\}  }"
    // This alias token's value will resolve to 99
  }
}
```

## Summary
As I mentioned at the start, I don't think the format needs to or should restrict what characters are allowed to be used in names. However, I do think we need to:

* Update our alias section to include a way of escaping special characters inside a reference, and to explicitly state that the segments must be exact matches to the names they reference
* Provide advice for authors to help them choose names that avoid the issues I've highlighted here

**Comment by kevinmpowell** [comment]
@c1rrus I like all of this, but I think it's reasonable for us to exclude a small set of symbols that we need to keep aliasing or other functionality clean. A rule like: 

"$,{, and } cannot be used within a token name"

Seems reasonable to me, and I don't think it's limiting.

**Comment by ChucKN0risK** [comment]
Is there a specific reason why you added `$` in the set of escaped characters @kevinmpowell? Is it related to Sass variables?

**Comment by kevinmpowell** [comment]
Not related to sass, previously we'd discussed an alias syntax that included `$`. That's not in the current spec, so `$` doesn't need to be excluded.

**Comment by dbanksdesign** [comment]
There is an issue on Style Dictionary about escaping the curly braces so the user could have a templated string as a token value: https://github.com/amzn/style-dictionary/issues/334 We might not want to support that use-case, but something to bring up. I do like the idea of having invalid characters to be explicit, and maybe space character should be one of them? I'm thinking every language I can think of does not allow space characters for a variable name. Also I tried to find part of the CSS spec that had rules for custom property names and couldn't find anything: https://www.w3.org/TR/css-variables-1/#defining-variables

**Comment by dbanksdesign** [comment]
Reviewed by the spec editors on 2021-11-02

**Decision**

Due to implications on alias resolution, the specification should include name character restrictions. The first restricted characters could be `.`, `{`, and `}`, but may include more. We will look for feedback from vendors and toolmakers and discuss these changes further. The specification should also describe alias resolution in more depth to describe why these restrictions are needed. 

**Action to be taken**

Next version of specification will reflect these decisions.

We’ll leave this issue open for feedback on which characters to include.

**Comment by kaelig** [comment]
Reopening this issue as mentioned in https://github.com/design-tokens/community-group/issues/60#issuecomment-957965199
