### ISSUE TITLE
Are token descriptions optional or required?

### ISSUE THREAD

**Issue by kevinmpowell** [design-tokens/community-group#62]
## Are token descriptions optional or required?
```
{
  colorTextPrimary: {
    value: '#000000',
    description: 'The text color most commonly used in the design system.'
  }
}
```

**Comment by kevinmpowell** [comment]
I vote optional.

**Comment by ariarzer** [comment]
I vote required.

As developer must description all their component, so should designer description all their tokens.

When we started using our token system in the web (after mobiles), I had to make several meetings with designers for collect a descriptions. Can see it there (in russian) https://ariarzer.github.io/tag_table/

And now, until we can't change the format of design system tokent, the descriptions are located in separate repository (https://github.com/ariarzer/tag_table/blob/master/data/data.json)/

It is very uncomfortable.

**Comment by gossi** [comment]
If they are required, there will be plenty empty strings: 

```
{
  "description": ""
}
```

will become the most commonly used description. So I'm for optional as @kevinmpowell. Provide a description, when there is something to describe. Ideally, the name is already the best description 🙈

**Comment by jina** [comment]
I vote optional. Depending on your naming and organization conventions, you may not need a description. But they're nice to have when your names/organization are not self-documenting.

**Comment by dom1n1k** [comment]
Definitely optional. But you can use a linter for warnings/errors/etc.

**Comment by christianmartinnies** [comment]
I vote for required.
Reason for that is better communication between disciplines. I assume, we can move a lot of additional discussion into a formalized process. I know, it may be perceived as additional workload/overhead but once agreed upon, anyone will benefit. :)

Of course there may be empty values, but this should be taken as a signal for either incomplete work or insecure about, what exactly to define…
As speaking from a developer's perspective, i would love to know the reason behind each decision in order to be able to compose without the need of guessing.
This may lead to lower acceptance overall but to me it would be worth it.

**Comment by bellentani** [comment]
I vote optional.

As much as we want all tokens to have descriptions, we can have items that repeat or will end up being filled with dome patterns `description: ""` (which will happen a lot, I'm sure). We can create the idea of "optional but highly recommended".

We know that many tokens can repeat themselves or get vague descriptions for the criteria to be fulfilled, and the description should be more of a helping tool than a bureaucratic process just to fulfill a good practice.

It would be similar to accepting an intermediate format over a strict one (as with XHTML).

**Comment by christianmartinnies** [comment]
See your points, good ones. Maybe i am a bit biased… ;)
Testing for empty values can be tested automatically so we would be able to measure the quality. This is implementation, individual QA and may vary by use cases.
Therefore i also go with "optional but highly recommended".

**Comment by kevinmpowell** [comment]
Reviewed by the spec editors on 2021-10-19. 

**Decision** 
Token descriptions _are_ optional. 

**Decision**
Descriptions can be added at the file and group level. Follow #72 for further details.

**Action to be taken**
Next version of specification will include these decisions. @kaelig's [comments](https://github.com/design-tokens/community-group/issues/62#issuecomment-936737270) will be included with the specification update.

**Comment by delisma** [comment]
@kevinmpowell Sorry to be late to the conversation, but is there a way to consider multilingual support in the next proposal of the specification? At the Government of Canada we are mandated to maintain bilingual documentation. So making the description property just a plain JSON string, is a bit problematic when we intend to use it like this:
```
{
  "Button background": {
    "value": "#777777",
    "description": {
      "en": "The background colour for buttons in their normal state.",
      "fr": "La couleur de fond des boutons dans leur état normal."
    }
  }
}
```

**Comment by kevinmpowell** [comment]
@delisma That's a good use case to be aware of. I'll bring this up with the editors.

**Comment by delisma** [comment]
@kevinmpowell Do you know when we could expect a new draft of the specification?

**Comment by duboisp** [comment]
Instead of reinventing the wheel for how to apply multilingual (known as internationalization or i18n) I suggest to upgrade the JSON format of the design token for a JSON-LD format. That way it become easier to implement multilingual need. 
reference: https://www.w3.org/TR/json-ld/#string-internationalization 

The following example are only limited to illustrate how JSON-LD notation can be used to express multilingual value.

Specify a default language for design token description to be French:
```json
{
  "@context" : {
    "@version": "1.1",
    "@language": "fr",
  }
  "Button background": {
    "value": "#777777",
    "description": "La couleur de fond des boutons dans leur état normal."
  }
}
```
reference: https://www.w3.org/TR/json-ld/#example-68-setting-the-default-language-of-a-json-ld-document

Specify a default language for design token description to be English but contain an alternate French description:
```json
{
  "@context" : {
    "@version": "1.1",
    "@language": "en",
  }
  "Button background": {
    "value": "#777777",
    "description": [
      {
        "@value": "The background colour for buttons in their normal state."
      },
      {
        "@value": "La couleur de fond des boutons dans leur état normal.",
        "@language": "fr"
      }
    ]
  }
}
```
reference: https://www.w3.org/TR/json-ld/#example-79-using-an-expanded-form-to-set-multiple-values

Specify language by leveraging sub-property inside the description property:
```json
{
  "@context" : {
    "@version": "1.1",
    "@language": "en",
    "description": {
      "@id": "https://design-tokens.github.io/community-group/format/#description",
      "@container": "@language"
    }
  }
  "Button background": {
    "value": "#777777",
    "description": {
      "en": "The background colour for buttons in their normal state.",
      "fr": "La couleur de fond des boutons dans leur état normal."
    }
  }
}
```
reference: https://www.w3.org/TR/json-ld/#example-71-language-map-expressing-a-property-in-three-languages

\cc @delisma @kevinmpowell

**Comment by delisma** [comment]
@duboisp [Section 4](https://design-tokens.github.io/community-group/format/#file-format) of the draft explain why the community group is choosing JSON as the standard file format"
> - Broad support in many programming languages’ standard libraries. This is expected to lower barriers to entry for developers writing software that supports design token files.
> - Current popularity and widespread use. This is expected to lower the learning curve as many people will already be familiar with JSON.
> - Being text-based (rather than binary) allows hand-editing design token files without needing specialized software other than a basic text editor. It also means the files are somewhat human-readable.

Do you think that JSON-LD has a broad support with current tools and librairies? And I'm not expecting designers to know JSON, yet again JSON-LD, but the learning curve is much lower for the non-developer audience.

**Comment by duboisp** [comment]
@delisma a JSON-LD document is a [conforming JSON document](https://www.w3.org/TR/json-ld/#abstract). 
> The syntax is designed to easily integrate into deployed systems that already use JSON, and provides a smooth upgrade path from JSON to JSON-LD.

The difference is an JSON-LD document are a contextualized JSON document and become more flexible because of the relation established between the JSON property name and a vocabulary term. (Linked Data)

There is several existing developer libraries that already support JSON-LD - https://json-ld.org/#developers

> And I'm not expecting designers to know JSON

The JSON format defined/used by this design token specification is intended for being implemented by developer that know JSON as mentioned in the first bullet in [Section 4](https://design-tokens.github.io/community-group/format/#file-format): "for **developers writing software** that supports design token files"

The discussion of using or not JSON-LD for design-token belong to another thread/discussion. My point was only to mention that the multilingual feature is already supported for JSON-LD documents and it is possible to upgrade JSON document into JSON-LD document.

**Comment by c1rrus** [comment]
Excellent points about supporting i18n and how JSON-LD could provide an established means to do so. Thanks @delisma and @duboisp for bringing these points to our attention!

I do wonder if basing our design token format on JSON-LD might add more complexity than we need. Based on the examples in @duboisp's comment and a brief skim of the JSON-LD spec, it looks like there are potentially quite a few different ways of expressing the same data by using (or not) `@context`. While it's pretty nifty, I wonder if it would steepen the learning curve for anyone wanting to manually read/write design token files. They'd need to familiarise themselves with JSON-LD as well as whatever design token specific conventions (or would that be a context or vacabulary?) we layer on top of it.

If I've understood JSON-LD correctly (and please do correct me if I haven't!), we may also need to re-think to how we express the data model described by our design token format. As it stands our design token format describes a fairly basic tree structure with 2 kinds of nodes: groups and tokens. Tokens are always leaf nodes and groups can have tokens and/or other groups as child nodes. That parent-child relationship is implicit in the nesting of JSON objects. Can we do that in JSON-LD? Or would we need to define some kind of explicit "child of" /"parent of" predicate that needs to then be used?

However, be it by using JSON-LD or creating our own mechanism, I am wondering if we need a means for internationalized text values not just for `description` but any token or group property that has human-readable text as its value. The current spec draft doesn't list any other than `description` right now, but there has been talk of adding things like deprecation notes in the future and I could imagine being able to provide those in more than one language could be handy too.

Going back to @delisma's original suggestion (which is also very similar to the last JSON-LD example in @duboisp's comment) I wonder if could simply say that the value of a description (and any other props with human-readable text values we may add in future) can be either a JSON string or a JSON object whose properties are language identifiers and corresponding values are strings. E.g.:

```json
{
  "token 1": {
    "value": 123,
    "description": "I am a description whose language has not been explicitly identified"
  },
  "token 2": {
    "value": 321,
    "description": {
      "en": "I am an English description",
      "de": "Ich bin eine deutsche Beschreibung"
    }
  }
}
```

**Comment by kevinmpowell** [comment]
I'm closing this issue in favor of a new RFC issue.

Description will remain an optional field in the spec. Whether or not it supports multiple languages can be discussed further here: https://github.com/design-tokens/community-group/issues/84
